-- MySQL Script generated by MySQL Workbench
-- Tue Nov 25 14:28:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
 
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
 
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
 
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;
 
-- -----------------------------------------------------
-- Table `mydb`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlogin`))
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `mydb`.`klant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`klant` (
  `idklant` INT NOT NULL AUTO_INCREMENT,
  `Naam` VARCHAR(45) NOT NULL,
  `leeftijd` VARCHAR(45) NOT NULL,
  `woonplaats` VARCHAR(45) NOT NULL,
  `login_idlogin` INT NOT NULL,
  PRIMARY KEY (`idklant`),
  INDEX `fk_klant_login1_idx` (`login_idlogin` ASC) VISIBLE,
  CONSTRAINT `fk_klant_login1`
    FOREIGN KEY (`login_idlogin`)
    REFERENCES `mydb`.`login` (`idlogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `prijs` DECIMAL NOT NULL,
  `bestelling_idproducten` INT NOT NULL,
  `bestelling_klant_idklant` INT NOT NULL,
  `bestelling_klant_idlogin` INT NOT NULL,
  PRIMARY KEY (`idproduct`))
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `mydb`.`aanbiedingen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aanbiedingen` (
  `idaanbiedingen` INT NOT NULL AUTO_INCREMENT,
  `korting` INT NULL DEFAULT NULL,
  `product_idproduct` INT NOT NULL,
  PRIMARY KEY (`idaanbiedingen`),
  INDEX `fk_aanbiedingen_product1_idx` (`product_idproduct` ASC) VISIBLE,
  CONSTRAINT `fk_aanbiedingen_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `mydb`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `mydb`.`klant_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`klant_has_product` (
  `klant_idklant` INT NOT NULL,
  `product_idproduct` INT NOT NULL,
  PRIMARY KEY (`klant_idklant`, `product_idproduct`),
  INDEX `fk_klant_has_product_product1_idx` (`product_idproduct` ASC) VISIBLE,
  INDEX `fk_klant_has_product_klant1_idx` (`klant_idklant` ASC) VISIBLE,
  CONSTRAINT `fk_klant_has_product_klant1`
    FOREIGN KEY (`klant_idklant`)
    REFERENCES `mydb`.`klant` (`idklant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_klant_has_product_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `mydb`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
 