-- MySQL Script generated by MySQL Workbench
-- Tue Nov 25 14:28:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
 
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
 

-- Application users test data
-- wachtwoord helloworld
INSERT INTO `users` (username,displayname,passwordhash) VALUES ('leraar','mario','$argon2id$v=19$m=65536,t=4,p=1$Zm9Cc0IwQ3BDLzRSaVIvYw$attCFRn94QfWxMObfoDrLtZ7emSPJjFl+AsqHGuQGAo');
 INSERT INTO `users` (username,displayname,passwordhash) VALUES ('jesper','goat','goated');