-- MySQL Script generated by MySQL Workbench
-- Tue Dec  2 15:30:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
 
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
 
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
 
-- -----------------------------------------------------
-- Table `login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlogin`))
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `klant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `klant` (
  `idklant` INT NOT NULL AUTO_INCREMENT,
  `Naam` VARCHAR(45) NOT NULL,
  `leeftijd` VARCHAR(45) NOT NULL,
  `woonplaats` VARCHAR(45) NOT NULL,
  `login_idlogin` INT NOT NULL,
  PRIMARY KEY (`idklant`),
  INDEX `fk_klant_login1_idx` (`login_idlogin` ASC) VISIBLE,
  CONSTRAINT `fk_klant_login1`
    FOREIGN KEY (`login_idlogin`)
    REFERENCES `login` (`idlogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `prijs` DECIMAL NOT NULL,
  PRIMARY KEY (`idproduct`))
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `aanbiedingen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aanbiedingen` (
  `idaanbiedingen` INT NOT NULL AUTO_INCREMENT,
  `korting` INT NULL DEFAULT NULL,
  `product_idproduct` INT NOT NULL,
  PRIMARY KEY (`idaanbiedingen`),
  INDEX `fk_aanbiedingen_product1_idx` (`product_idproduct` ASC) VISIBLE,
  CONSTRAINT `fk_aanbiedingen_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `klant_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `klant_has_product` (
  `klant_idklant` INT NOT NULL,
  `product_idproduct` INT NOT NULL,
  PRIMARY KEY (`klant_idklant`, `product_idproduct`),
  INDEX `fk_klant_has_product_product1_idx` (`product_idproduct` ASC) VISIBLE,
  INDEX `fk_klant_has_product_klant1_idx` (`klant_idklant` ASC) VISIBLE,
  CONSTRAINT `fk_klant_has_product_klant1`
    FOREIGN KEY (`klant_idklant`)
    REFERENCES `klant` (`idklant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_klant_has_product_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `product_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_type` (
  `idproduct_type` INT NOT NULL AUTO_INCREMENT,
  `groente` VARCHAR(45) NOT NULL,
  `fruit` VARCHAR(45) NOT NULL,
  `product_idproduct` INT NOT NULL,
  PRIMARY KEY (`idproduct_type`, `product_idproduct`),
  INDEX `fk_product_type_product1_idx` (`product_idproduct` ASC) VISIBLE,
  CONSTRAINT `fk_product_type_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
 